#What is NumPy?

NumPy is a Python library.NumPy is used for working with arrays.NumPy is short for
"Numerical Python". It also has functions for working in domain of linear algebra, fourier
transform, and matrices.NumPy was created in 2005 by Travis Oliphant. It is an open source
project and you can use it freely.

#Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.NumPy
aims to provide an array object that is up to 50x faster than traditional Python lists.The array
object in NumPy is called ndarray, it provides a lot of supporting functions that make
working with ndarray very easy.Arrays are very frequently used in data science, where speed
and resources are very important.

In [ ]:
!Pip install numpy

/bin/bash: line 1: Pip: command not found


In [ ]:
import numpy as np
print (np.__version__)


1.23.5


In [ ]:
#0 D array or scalars
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [ ]:
list = [1,2,3,4]
print(type(list))

<class 'list'>


In [ ]:
#1D array or uni-dimentional array
arr_1 = np.array([1,2,3,4,5])
print(arr_1)
print(type(arr_1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#2D array or matrix or 2nd order tensor
arr_2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#3d array or 3rd order tensor
arr_3 = np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])
print(arr_3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 7  8  9 10]
  [ 4  5  6  7]]]


In [ ]:
#dimensions
a= np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[5,6,7,8]])
d= np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#5d array
arr_5 = np.array([1,2,3,4],ndmin =5)
print(arr_5)
print(arr_5.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
#acess
b = np.array([1,2,3,4,5])#0,1,2,...n
print(b[-1])
print(b[0]+b[1])
print(b[0]-b[1])

5
3
-1


In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c[1,-1])
print(c[:,:])

8
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#3d array
d= np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])
print(d[1,0,3])
print(d[1,0,-1])
print(d[1,0,:])

10
10
[ 7  8  9 10]


In [ ]:
b = np.array([1,2,3,4,5])
reve  = b[::-1]
print(reve)


[5 4 3 2 1]


In [ ]:
b = np.array([1,2,3,4,5])
c  = b[5:1]
print(c)

[]


In [ ]:
#SLICING

b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[5,6,7,8]])
d= np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])
print(b[:3])
print(c[0,:])
print(d[0,1,:])

[1 2 3]
[1 2 3 4]
[5 6 7 8]


i - integer

 b - boolean

 u - unsigned integer

 f - float

 c - complex float

 m - timedelta

 M - datetime

 O - object

 S - string

 U - unicode string

 V - fixed chunk of memory for other type ( void )

In [ ]:
arr = np.array([1,2,3,4])
str = np.array(['apple','banana'])
print(arr.dtype)
print(str.dtype)

int64
<U6


In [ ]:
arr = np.array([1,2,3,4],dtype = 'i4')
print(arr.dtype)

int32


In [ ]:
p = np.array([1.2,2.3,3.1,4.2])
print(p)
print(p.dtype)

[1.2 2.3 3.1 4.2]
float64


In [ ]:
newarr = p.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [ ]:
#copy
arr = np.array([1,2,3,4])
x = arr.copy()
y = np.copy(arr)

x[0] = 42
print(x)
print(y)
print(arr)


[42  2  3  4]
[1 2 3 4]
[1 2 3 4]


In [ ]:
#view
arr = np.array([1,2,3,4])
print(arr)
x = arr.view()
x[0] = 42
print(x)
print(arr)


[1 2 3 4]
[42  2  3  4]
[42  2  3  4]


In [ ]:
ab = np.array([[1,2,3,4],[5,6,7,8]])
print(ab.shape)


(2, 4)


In [ ]:
arr = np.array([1,2,3,4,5,7,8,98,4,5,10,4])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  7]
 [ 8 98  4]
 [ 5 10  4]]


In [ ]:
arr = np.array([1,2,3,4,5,7,8,98,4,5,10,4])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  7]]

 [[ 8 98]
  [ 4  5]
  [10  4]]]


In [ ]:
ab = np.array([[1,2,3,4],[5,6,7,8]])
dc = arr.reshape(-1)
print(dc)


[ 1  2  3  4  5  7  8 98  4  5 10  4]


In [ ]:

#c = np.array([[1,2,3,4],[5,6,7,8]])
#d= np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])

b = np.array([1,2,3,4,5])
for i in b:
  print(i)

1
2
3
4
5


In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
for i in c:
  for j in i:
   print(j)

1
2
3
4
5
6
7
8


In [ ]:
d= np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])
for i in d:
    for j in i:
      for k in j:
        print(k)

1
2
3
4
5
6
7
8
7
8
9
10
4
5
6
7


In [ ]:
d= np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])
for x in np.nditer(d):
  print(x)

1
2
3
4
5
6
7
8
7
8
9
10
4
5
6
7


In [ ]:
d= np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[4,5,6,7]]])
for x in np.nditer(d,flags= ['buffered'],op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'7'
b'8'
b'9'
b'10'
b'4'
b'5'
b'6'
b'7'


In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[2,8,5,4],[5,9,7,8]])
arr = np.concatenate((c,d))
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [2 8 5 4]
 [5 9 7 8]]


In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[2,8,5,4],[5,9,7,8]])
arr = np.stack((c,d))
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[2 8 5 4]
  [5 9 7 8]]]


In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[2,8,5,4],[5,9,7,8]])
arr = np.hstack((c,d))
print(arr)

[[1 2 3 4 2 8 5 4]
 [5 6 7 8 5 9 7 8]]


In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[2,8,5,4],[5,9,7,8]])
arr = np.vstack((c,d))
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [2 8 5 4]
 [5 9 7 8]]


In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[2,8,5,4],[5,9,7,8]])
arr = np.dstack((c,d))
print(arr)

[[[1 2]
  [2 8]
  [3 5]
  [4 4]]

 [[5 5]
  [6 9]
  [7 7]
  [8 8]]]


In [ ]:
c = np.array([1,2,3,4])
newarr = np.array_split(c,2)
print(newarr[0])

[1 2]


In [ ]:
c = np.array([1,2,3,4])
x = np.where(c%2 ==0)
print(x)


(array([1, 3]),)


In [ ]:
c = np.array([1,2,3,4,3])
x = np.searchsorted(c,2,side ='right')
print(x)

2


In [ ]:
c = np.array([1,2,3,4,7,6,5])
arr = np.sort(c)
print(arr)

[1 2 3 4 5 6 7]


In [ ]:
arr = np.array([41,42,43,45])
filter_arr = arr>42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 45]
